apiVersion: v1
kind: Service
metadata:
  name: ivolve-service
  namespace: ivolve
  labels:
    app: ivolve-app
spec:
  type: LoadBalancer
  selector:
    app: ivolve-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
